export default {
    products: [{
        _id:'1',
        name: 'WC 200 blaða',
        categories: 'pappír',
        image: '/images/WC_200_blada.JPG',
        price: '3.700',
        brand: 'Papco',
        rating: '2ja laga - 200 blaða, 48 rúllur - 24 metrar á rúllur',
    },
    {
        _id:'2',
        name: 'WC 500 blaða',
        categories: 'pappír',
        image: '/images/WC_500_blada.JPG',
        price: '4.000',
        brand: 'Papco',
        rating: '2ja laga - 500 blaða, 30 rúllur - 55 metrar á rúllur',
    },
    {
        _id:'3',
        name: 'WC Lúxus pappír',
        categories: 'pappír',
        image: '/images/WC_luxus.JPG',
        price: '3.500',
        brand: 'Papco',
        rating: '3ja laga - 200 blaða, 32 rúllur - 21 metrar á rúllur',
    },
    {
        _id:'4',
        name: 'Eldhúsrúllur',
        categories: 'pappír',
        image: '/images/Eldhusrullur.JPG',
        price: '3.000',
        brand: 'Papco',
        rating: '2ja laga - 50 blaða, 24 rúllur - 12 metrar á rúllur',
    },
    {
        _id:'5',
        name: 'Eldhúsrúllur hálfskiptar',
        categories: 'pappír',
        image: '/images/Eldhusrullur_halfskiptar.JPG',
        price: '3.200',
        brand: 'Papco',
        rating: '2ja laga - 200 blaða, 16 rúllur - 24 metrar á rúllur',
    },
    {
        _id:'6',
        name: 'Papco sorppokar',
        categories: 'ýmislegt',
        image: '/images/sorppokar.JPG',
        price: '1.500',
        brand: 'Papco',
        rating: '25 stk. á rúllu, 75x120 cm ',
    },
    {
        _id:'7',
        name: 'Harðfiskur',
        categories: 'ýmislegt',
        image: '/images/hardfiskur.JPG',
        price: '2.000 ',
        brand: 'Papco',
        rating: 'Þorskur 150 gr., roð og beinlaus',
    },
    {
        _id:'8',
        name: 'Papco Kerti',
        categories: 'jól',
        image: '/images/kerti.JPG',
        price: '2.000',
        brand: 'Papco',
        rating: 'Kertapakki inniheldur: Teljós 6 tíma - 50 stk í pokka. Kubbakerti - 7x15cm - 1 stk. Kubbakerti - 8x25cm - 1 stk',
    },
    {
        _id:'9',
        name: 'Jólapappír',
        categories: 'jól',
        image: '/images/jolapappir.JPG',
        price: '1.500',
        brand: 'Papco',
        rating: '4 rúllur, 7 stk slaufur, 2 stk band',
    },
    {
        _id:'10',
        name: 'Útikerti',
        image: '/images/Utikerti.PNG',
        price: '1.000',
        brand: 'Papco',
        rating: '2 Útikerti 100x46 mm',
    },
    {
        _id:'11',
        name: 'Góu Lakkrís',
        categories: 'nammi',
        image: '/images/Goa.jpg',
        price: '1.000',
        brand: 'Góa',
        rating: 'Blandaður 500 gr.',
    },
    {
        _id:'12',
        name: 'Sambó Lakkrís',
        categories: 'nammi',
        image: '/images/lakkris.JPG',
        price: '1.000',
        brand: 'Sambó',
        rating: 'Blandaður 400 gr.',
    },
]
}